openapi: 3.0.1
info:
  title: BillStructureTelia
  description: This is an extended BillStructure schema containing nextCycleSpecification
  version: 4.0.0
components:
  schemas:
    BillFormatRefOrValue:
      required:
        - name
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the bill format
        href:
          type: string
          description: Reference of the bill format
        description:
          type: string
          description: An explanatory text for this bill format
        name:
          type: string
          description: A short descriptive name
        "@baseType":
          type: string
          description: When sub-classing, this defines the super-class
        "@schemaLocation":
          type: string
          description: A URI to a JSON-Schema file that defines additional attributes
            and relationships
          format: uri
        "@type":
          type: string
          description: When sub-classing, this defines the sub-class entity name
        "@referredType":
          type: string
          description: The actual type of the target instance when needed for disambiguation.
      description: An attachment by value or by reference.
    BillPresentationMediaRefOrValue:
      required:
        - name
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the bill presentation media
        href:
          type: string
          description: Reference of the bill presentation media
        description:
          type: string
          description: An explanatory text describing this bill presentation media
        name:
          type: string
          description: A short descriptive name
        "@baseType":
          type: string
          description: When sub-classing, this defines the super-class
        "@schemaLocation":
          type: string
          description: A URI to a JSON-Schema file that defines additional attributes
            and relationships
          format: uri
        "@type":
          type: string
          description: When sub-classing, this defines the sub-class entity name
        "@referredType":
          type: string
          description: The actual type of the target instance when needed for disambiguation.
      description: An attachment by value or by reference.
    BillStructure:
      type: object
      properties:
        cycleSpecification:
          $ref: "#/components/schemas/BillingCycleSpecificationRefOrValue"
        format:
          $ref: "#/components/schemas/BillFormatRefOrValue"
        presentationMedia:
          type: array
          items:
            $ref: "#/components/schemas/BillPresentationMediaRefOrValue"
        "@baseType":
          type: string
          description: When sub-classing, this defines the super-class
        "@schemaLocation":
          type: string
          description: A URI to a JSON-Schema file that defines additional attributes
            and relationships
          format: uri
        "@type":
          type: string
          description: When sub-classing, this defines the sub-class entity name
      description: The structure of the bill for party accounts (billing or settlement).
    BillStructureTelia:
      allOf: # Combines the BasicErrorModel and the inline model
        - $ref: "#/components/schemas/BillStructure"
        - type: object
          properties:
            nextCycleSpecification:
              $ref: "#/components/schemas/BillingCycleSpecificationRefOrValue"
    BillingCycleSpecificationRefOrValue:
      required:
        - name
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the billing cycle specification
        href:
          type: string
          description: Reference of the billing cycle specification
        billingDateShift:
          type: integer
          description: An offset of a billing/settlement date. The offset is expressed
            as number of days with regard to the start of the billing/settlement period.
        billingPeriod:
          type: string
          description: "A billing time period. It can be recurring, for example: week,
            month, quarter of year, year ."
        chargeDateOffset:
          type: integer
          description: An offset of a date through which charges previously received
            by the billing system will appear on the bill. The offset is expressed
            as number of days with regard to the start of the BillingPeriod.
        creditDateOffset:
          type: integer
          description: An offset of a date through which credits previously received
            by the billing system will appear on the bill. The offset is expressed
            as number of days with regard to the start of the BillingPeriod.
        dateShift:
          type: integer
          description: An offset of a billing/settlement date. The offset is expressed
            as number of days with regard to the start of the billing/settlement period.
        description:
          type: string
          description: An explanation regarding this billing cycle specification
        frequency:
          type: string
          description: Frequency of the billing cycle (monthly for instance)
        mailingDateOffset:
          type: integer
          description: An offset of a customer bill mailing date. The offset is expressed
            as number of days with regard to the start of the BillingPeriod.
        name:
          type: string
          description: A short descriptive name
        paymentDueDateOffset:
          type: integer
          description: An offset of a payment due date. The offset is expressed as
            number of days with regard to the start of the BillingPeriod.
        validFor:
          $ref: "#/components/schemas/TimePeriod"
        "@baseType":
          type: string
          description: When sub-classing, this defines the super-class
        "@schemaLocation":
          type: string
          description: A URI to a JSON-Schema file that defines additional attributes
            and relationships
          format: uri
        "@type":
          type: string
          description: When sub-classing, this defines the sub-class entity name
        "@referredType":
          type: string
          description: The actual type of the target instance when needed for disambiguation.
      description: An attachment by value or by reference.
    TimePeriod:
      type: object
      properties:
        endDateTime:
          type: string
          description: End of the time period, using IETC-RFC-3339 format
          format: date-time
        startDateTime:
          type: string
          description: Start of the time period, using IETC-RFC-3339 format. If you
            define a start, you must also define an end
          format: date-time
      description: A period of time, either as a deadline (endDateTime only) a startDateTime
        only, or both
