openapi: 3.0.1
info:
  title: BillStructureTelia
  description: This is an extended BillStructure schema containing nextCycleSpecification
  version: 4.0.0
paths:
  /dummy:
    get:
      summary: dummy
      responses:
        200:
          description: ok
components:
  schemas:
    BillStructureTelia:
      allOf:
        - $ref: "./Account.regular.r19.oas3.yaml#/components/schemas/BillStructure"
        - type: object
          properties:
            nextCycleSpecification:
              $ref: "#/components/schemas/BillingCycleSpecificationRefOrValue"
